
export const pageContent = {
  washPackages: [
    {
      title: "PREMIUM DETAIL",
      price: "$400.00+",
      duration: "8 hrs+",
      description: "Exterior: Detailed hand wash, chemical & mechanical decontamination, deep cleaning of wheels/tires, conditioning of plastics, 1-step polish, and 3-6 months ceramic coating. Interior: Deep vacuum, upholstery cleaning, carpet/mat cleaning, dashboard/console/door panel cleaning & protection, and window cleaning.",
    },
    {
      title: "FULL DETAILING",
      price: "$200.00+",
      duration: "3 hrs 30 mins+",
      description: "Exterior: Detailed hand wash, chemical & mechanical decontamination, Carnauba wax, deep cleaning of wheels/tires, and conditioning. Interior: Deep vacuum, upholstery cleaning, carpet/mat cleaning, and cleaning/protection of plastics.",
    },
    {
      title: "BASIC WASH",
      price: "$50.00+",
      duration: "1 hr+",
      description: "The perfect solution for weekly maintenance. Includes exterior hand wash, rim/tire cleaning, complete interior vacuum, and microfiber drying for a shiny finish.",
    },
  ],
  interiorAddons: [
    {
      title: "PET HAIR REMOVAL",
      price: "$20.00",
      duration: "1 hr",
      description: "Effectively removes pet hair from upholstery and carpets, leaving your interior spotless and free of allergens.",
    },
    {
      title: "UPHOLSTERY CONDITIONING",
      price: "$40.00",
      duration: "45 mins",
      description: "We moisturize all plastics and upholstery, keeping the interior hydrated and protected.",
    },
    {
      title: "DEEP UPHOLSTERY CLEANING",
      price: "$40.00+",
      duration: "30 mins+",
      description: "Uses the injection-extraction method to remove deep dirt. Price is $40-$75 per seat.",
    },
    {
      title: "HEADLINER CLEANING",
      price: "$150.00+",
      duration: "2 hrs+",
      description: "Specialized low-moisture technique with pH-neutral cleaners to safely treat delicate headliner fabrics.",
    },
  ],
  exteriorAddons: [
    {
      title: "CERAMIC COATING",
      price: "$400.00+",
      duration: "30 mins",
      description: "A liquid nanotechnology polymer that provides years of protection against UV rays, chemical stains, and dirt, with an extreme gloss and hydrophobic effect.",
    },
    {
      title: "ENGINE WASH",
      price: "$50.00",
      duration: "30 mins",
      description: "Safely remove grease, oil, and dirt buildup from the engine bay, improving aesthetics and helping to keep your vehicle in top condition.",
    },
    {
      title: "HEADLIGHTS RESTORATION",
      price: "$100.00",
      duration: "1 hr",
      description: "Restores clarity to foggy or yellowed headlights and includes a 1-year ceramic protection coating.",
    },
    {
      title: "PAINT CORRECTION",
      price: "$600.00+",
      duration: "5 hrs+",
      description: "An intensive process to remove 70-90% of visible defects like swirls, scratches, and water spots, restoring a mirror-like finish. Includes a 3-month sealant.",
    },
    {
      title: "WATER SPOT REMOVER",
      price: "$50.00",
      duration: "30 mins",
      description: "Specialized treatment to dissolve and remove hard water mineral deposits from paint and glass.",
    },
    {
      title: "ONE-STEP POLISHING",
      price: "$250.00+",
      duration: "5 hrs+",
      description: "Removes very light micro-scratches and minor oxidation to dramatically increase shine and color depth.",
    },
    {
      title: "CLAY BAR",
      price: "$50.00+",
      duration: "30 mins",
      description: "Removes embedded contaminants from the paint surface, leaving it incredibly soft and ready for waxing or sealing.",
    },
    {
      title: "WAX",
      price: "$30.00",
      duration: "30 mins",
      description: "Creates a deep, wet-look gloss, a protective barrier against UV rays, and a hydrophobic effect.",
    },
  ],
  hours: [
    { day: "Monday", time: "7:00 am - 5:00 pm" },
    { day: "Tuesday", time: "7:00 am - 5:00 pm" },
    { day: "Wednesday", time: "7:00 am - 5:00 pm" },
    { day: "Thursday", time: "7:00 am - 5:00 pm" },
    { day: "Friday", time: "7:00 am - 5:00 pm" },
    { day: "Saturday", time: "7:00 am - 5:00 pm" },
    { day: "Sunday", time: "7:00 am - 5:00 pm" },
  ],
  serviceAreas: [
    "Bell",
    "Bell Gardens",
    "Bellflower",
    "Carson",
    "Cudahy",
    "Downey",
    "El Segundo",
    "Gardena",
    "Hawthorne",
    "Hermosa Beach",
    "Huntington Park",
    "Inglewood",
    "Lakewood",
    "Lawndale",
    "Lomita",
    "Long Beach",
    "Lynwood",
    "Manhattan Beach",
    "Marina del Rey",
    "Palos Verdes Estates",
    "Paramount",
    "Playa del Rey",
    "Rancho Palos Verdes",
    "Redondo Beach",
    "San Pedro",
    "Santa Monica",
    "Signal Hill",
    "South Gate",
    "South LA",
    "Torrance",
    "Venice",
  ],
};
